config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#homepage'
  
  get 'mood/new', to: 'mood#new'
  post 'mood/new', to: 'mood#create'

  get 'food/new', to: 'food#new'
  post 'food/new', to: 'food#create'

  get 'habits/new', to: 'habits#new'
  post 'habits/new', to: 'habits#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  validates :entry_date, presence: true
  validates :title, presence: true
end

app/models/finance.rb
# frozen_string_literal: true

class Finance < ApplicationRecord
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  before_create :set_default_entry_datetime
  def set_default_entry_datetime
    self.entry_date = DateTime.now
  end
end

app/models/habits.rb
# frozen_string_literal: true

class Habits < ApplicationRecord
  HABIT_LIST = [
    'Read in the morning',
    'Yoga',
    'Run',
    '3 games of chess',
    'Focused work',
    'Push ups',
    'Plank'
  ]
end

app/models/mood.rb
# frozen_string_literal: true

class Mood < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def new
    @food = Food.new
  end
  
  def create
    @food = Food.new(mood_params)
    if @food.save
      redirect_to root_path
    else
      puts 'hello'
    end
  end

  def mood_params
    params.require(:food).permit(:title, :healthy, :entry_date)
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  def new
    @habits = Habits.new
  end
  
  def create
    @habits = Habits.new(habits_params)
    if @habits.save
      redirect_to root_path
    else
      render :new
    end
  end

  def habits_params
    params.require(:habits).permit(:title, :entry_date)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  ENTRY_MODELS = [Food, Finance, Mood, Habits].freeze

  def homepage
    @entries = ENTRY_MODELS.flat_map do |model|
      model.where(entry_date: DateTime.now.beginning_of_month.beginning_of_week..DateTime.now.end_of_month.end_of_week)
    end
  end
end

app/controllers/mood_controller.rb
class MoodController < ApplicationController
  def new
    @mood = Mood.new
  end
  
  def create
    @mood = Mood.new(mood_params)
    if @mood.save
      redirect_to root_path
    else
      'hello'
    end
  end

  def mood_params
    params.require(:mood).permit(:title, :entry_date)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/food/new.html.erb
<div class="container mt-5">
  <%= form_with model: @food, url: food_new_path  do |f| %>
    <div class="form-group">
      <%= f.label :food %>
      <%= f.text_field :title %>
    </div><br>


    <div>
      <%= f.label :entry_date, style: "display: block" %>
      <%= f.date_field :entry_date, :value => Time.now.strftime('%Y-%m-%d') %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  <% end%>

  <%= link_to 'Back', root_path %>
</div>

app/views/habits/new.html.erb
<div class="container mt-5">
  <%= form_with model: @habits, url: habits_new_path  do |f| %>
    <div class="form-group">
      <%= f.label :habits %>
      <% Habits::HABIT_LIST.each do |key| %>
      <%= f.check_box :title, { multiple: true }, key,  nil %>
        <%= f.label key %>
      <% end %>
    </div><br>


    <div>
      <%= f.label :entry_date, style: "display: block" %>
      <%= f.date_field :entry_date, :value => Time.now.strftime('%Y-%m-%d') %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  <% end%>

  <%= link_to 'Back', root_path %>
</div>

app/views/home/homepage.html.erb
<%= render 'partials/dropdown' %>
<%= render 'partials/form' %>



<div class="container mt-5 text-center">
  <h3>What have you done today?</h3>

<%= month_calendar(events: @entries, attribute: :entry_date) do |date, entries| %>
  <div class="day">
    <%= date.day %>
  </div>
  <% entries.each do |entry| %>
     <%# #something that will filter models by select %>
      <div class="card-header">
        <div class="card-title">
        <% if entry.class == Mood %>
            <%= entry.created_at.strftime("%I:00").to_i < 12 ? '(AM)' : '(PM)' %>
          <% end %>
          <%= entry.class %>:
          <%= entry.title %>
        </div>
      </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mood/new.html.erb
<div class="container mt-5">
  <%= form_with model: @mood, url: mood_new_path  do |f| %>
    <div class="form-group">
      <%= f.label :mood %> <br>
      <%= f.label :mood, "Red", value: "Red"  %>
      <%= f.radio_button :title, 'Red' %>
      <%= f.label :mood, "Amber", value: "Amber" %>
      <%= f.radio_button :title, 'Amber' %>
      <%= f.label :mood, "Green", value: "Green" %>
      <%= f.radio_button :title, 'Green' %>
    </div><br>


    <div>
      <%= f.label :entry_date, style: "display: block" %>
      <%= f.date_field :entry_date, :value => Time.now.strftime('%Y-%m-%d') %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  <% end%>

  <%= link_to 'Back', root_path %>
</div>

app/views/partials/_dropdown.html.erb
<div class="smallme position-relative mt-2">
  <select class="form-select form-select-sm" aria-label=".form-select-sm example" onchange="if (this.value) window.location.href=this.value">
    <option selected>Select a tracker</option>
    <option value="1">Food</option>
    <option value="2">Finances</option>
    <option value="3">Mood</option>
    <option value="4">Habits</option>
  </select>
</div>

app/views/partials/_form.html.erb
<div class='container mt-3'><%= link_to 'New Mood Entry', mood_new_path %>
</div>

<div class='container mt-3'><%= link_to 'New Food Entry', food_new_path %>
</div>

<div class='container mt-3'><%= link_to 'New Habits Entry', habits_new_path %>
</div>